# Ideally we need to build and test but for this demo, I am sticking to only build image and publish.


on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main   
  jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Build and tag game service
          run: docker buildx build --platform linux/amd64 --tag shreenidhidev/game-service:v1 ./game-service

        - name: Build and tag auth service
          run: docker buildx build --platform linux/amd64 --tag shreenidhidev/auth-service:v1 ./auth-service
        
        - name: Build and tag frontend
          run: docker buildx build --platform linux/amd64 --tag shreenidhidev/frontend:v1 ./frontend/
    login:
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    publish:
      steps:
        - name: Push game service
          run: docker push shreenidhidev/game-service:v1
        - name: Push auth service
          run: docker push shreenidhidev/auth-service:v1        
        - name: Push frontend
          run: docker push shreenidhidev/frontend:v1          
      

       
      